### ISSUE TITLE
(Build) Spider2 not building on Windows VS19.

### ISSUE THREAD

**Issue by kdesnos** [preesm/spider2#10]
Current version of the code does not compile on windows 10 with MSVC 2019.
Errors causing this failure can be checked through the setupWindowsCI branch (d80e3c3) and the corresponding [log of travis build](https://travis-ci.com/github/preesm/spider2/jobs/320080148).

**Comment by farresti** [comment]
fixed with pull request https://github.com/preesm/spider2/pull/11
